### ISSUE TITLE
Bot does not send messages to the text channel

### ISSUE THREAD

**Issue by MRSEEO** [drizzle-mizzle/CharacterAI-Discord-Bot#10]
The bot accepts messages, sets the status "typing", but as a result, messages do not come to the text channel. There is a new version of the bot, I installed other chatbots and rebooted the bot several times. Nothing helps.

**Comment by drizzle-mizzle** [comment]
Починил
[1.66](https://github.com/drizzle-mizzle/CharacterAI-Discord-Bot/releases/tag/1.66)

**Comment by MRSEEO** [comment]
> Починил [1.66](https://github.com/drizzle-mizzle/CharacterAI-Discord-Bot/releases/tag/1.66)

Отвечает один раз и опять умирает. Отвечает либо после ресета, либо после полной перезагрузки...

**Comment by drizzle-mizzle** [comment]
Пока не выходит воспроизвести...

**Comment by drizzle-mizzle** [comment]
@MRSEEO так и не вышло наткнуться на проблему. Возможно, это были просто какие-то проблемы с серверами.
Попробуй загрузить последнюю версию и проверить ещё раз.

**Comment by MRSEEO** [comment]
> @MRSEEO так и не вышло наткнуться на проблему. Возможно, это были просто какие-то проблемы с серверами. Попробуй загрузить последнюю версию и проверить ещё раз.

Да, сервер видимо умирал. Теперь всё хорошо работает. Спасибо!
