### ISSUE TITLE
Help Running this on Replit?

### ISSUE THREAD

**Issue by NotLanden** [drizzle-mizzle/CharacterAI-Discord-Bot#101]
Hello, I'm trying to run this on replit so that I can run it 24/7 for free. Im having an issue trying to run it as both an exe and as c# code from the source code. Any help is appreciated.

**Comment by drizzle-mizzle** [comment]
You can't run it on replit.

**Comment by NotLanden** [comment]
Why not?

**Comment by drizzle-mizzle** [comment]
Replit won't allow you to install needed dependencies on it

**Comment by drizzle-mizzle** [comment]
As I know, there's no way to install apt packages on it. Read https://github.com/drizzle-mizzle/CharacterAI-Discord-Bot/wiki/How-to-set-up#linux

**Comment by MeeIIs635** [comment]
So, how would I go about running it 24/7 even with my PC off?

**Comment by drizzle-mizzle** [comment]
any VPS actually

**Comment by MeeIIs635** [comment]
Ok but which ones? Free ones
