### ISSUE TITLE
[proxy mode Feature request]

### ISSUE THREAD

**Issue by lussifa** [drizzle-mizzle/CharacterAI-Discord-Bot#102]
- I am using the [latest version](https://github.com/drizzle-mizzle/CharacterAI-Discord-Bot/releases/latest) of the program.
-  I have read the [Additional-configuration](https://github.com/drizzle-mizzle/CharacterAI-Discord-Bot/wiki/Additional-configuration) page completely and made sure that this feature is not already implemented.
-  I have read the [Commands](https://github.com/drizzle-mizzle/CharacterAI-Discord-Bot/wiki/Commands) page completely and made sure that this feature is not already implemented.

### Description:
i use a proxy server in a LAN network, whatever i use 
"export https_proxy=http://x.x.x.x:8080 and export http_proxy=http://x.x.x.x:8080" 
or use proxychains4. 
it always shows
"05:09:08 Gateway     System.Net.Http.HttpRequestException: Resource temporarily unavailable (discord.com:443)“
but i am sure my proxy server working.
I try using curl via my proxy server to any website, it working normally.

**Comment by drizzle-mizzle** [comment]
I don't thing I can do anything about it, this project uses a barebone Discord.Net API wrapper. It's either problem with it, or with Discord API itself.

**Comment by drizzle-mizzle** [comment]
> Why would you want a proxy on it?

Maybe, Discord is blocked in his region, or some other services that he has to use on his machine, thus he has a system-wide proxy setup.

Still, it's not related to the project, I'm not a VPN provider. You will have to deal with it on your own.
