### ISSUE TITLE
[Feature request] New ARM version???

### ISSUE THREAD

**Issue by Dobikot** [drizzle-mizzle/CharacterAI-Discord-Bot#103]
- [x] I am using the [latest version](https://github.com/drizzle-mizzle/CharacterAI-Discord-Bot/releases/latest) of the program.
- [x] I have read the [Additional-configuration](https://github.com/drizzle-mizzle/CharacterAI-Discord-Bot/wiki/Additional-configuration) page completely and made sure that this feature is not already implemented.
- [x] I have read the [Commands](https://github.com/drizzle-mizzle/CharacterAI-Discord-Bot/wiki/Commands) page completely and made sure that this feature is not already implemented.

### Description:
How about to compile a ARM version? I have a Rasberry Pi, and yes. There exist a ARM version. But it's outdated. So, why not compile a new one?
Как насчёт ARM версии? И я знаю что уже есть ARM версия, но она устаревшая. Тем более, это поможет другим тем, что они смогут использовать Android телефоны, как сервера.
(Sorry for bad english, and my stupedness.)

**Comment by justkorudev** [comment]
I believe you can use box64/box86 and run the normal Linux version.
