### ISSUE TITLE
[IMPORTANT/BUG]

### ISSUE THREAD

**Issue by ColorsCrypt** [drizzle-mizzle/CharacterAI-Discord-Bot#106]
- [x] I am using the [latest version](https://github.com/drizzle-mizzle/CharacterAI-Discord-Bot/releases/latest) of the program.
- [x] I have read the [Known-issues](https://github.com/drizzle-mizzle/CharacterAI-Discord-Bot#known-issues) section and [Issues](https://github.com/drizzle-mizzle/CharacterAI-Discord-Bot/issues) page, and made sure that this problem was not already described elsewhere.

### Describe the bug:
The bot can be used to mass ping (for example @everyone or even larger ping strings)

### Steps to reproduce the behavior:
1. Go to any channel that where to bot has SEND_MESSAGE Permissions
2. Tell him to send a specific string(For example: @ai Reply with @everyone)
3. If the bot does it wron correct him 
4. Bot will Mass Ping Users

### Expected behavior:
"Block" or disable the pings in some way. This is a critical bug, you can really mass ping in all servers the bot is used in

### Screenshots:
![image](https://github.com/drizzle-mizzle/CharacterAI-Discord-Bot/assets/126079750/15095ebd-e477-4cad-9c3b-57a85ff39e22)

**Comment by drizzle-mizzle** [comment]
\> Important!
\> **critical** bug!
Dude. That's not even funny.
Just don't give your bot the permission to call `@everyone` and `@here`
[How To Set Up Server Permissions](https://support.discord.com/hc/en-us/articles/206029707-Setting-Up-Permissions-FAQ)

ffs...
![image](https://github.com/drizzle-mizzle/CharacterAI-Discord-Bot/assets/55811932/9008b1bf-2765-481c-b522-9ebc4d4b505d)

**Comment by drizzle-mizzle** [comment]
What are you talking about? How can it mass ping anyone if you won't allow it to?
