### ISSUE TITLE
[BUG] Opening two instances results in only one of them working

### ISSUE THREAD

**Issue by m3t4f1v3** [drizzle-mizzle/CharacterAI-Discord-Bot#111]
- [x] I am using the [latest version](https://github.com/drizzle-mizzle/CharacterAI-Discord-Bot/releases/latest) of the program.
- [x] I have read the [Known-issues](https://github.com/drizzle-mizzle/CharacterAI-Discord-Bot#known-issues) section and [Issues](https://github.com/drizzle-mizzle/CharacterAI-Discord-Bot/issues) page, and made sure that this problem was not already described elsewhere.

### Describe the bug:
Opening a bot with a distinct set of tokens (including the same or dissimilar char_ai_user_tokens) results in only one working, even resulting in others not responding to things like .ai ping.

### Steps to reproduce the behavior:
1. Open one instance of a bot
2. Open a second instance of a bot
3. .ai ping
4. Only one seems to respond

### Expected behavior:
Both bot users responding

### Additional info:
- Arch Linux

**Comment by drizzle-mizzle** [comment]
I'm sure you have simply forget to give your second bot all nedeed permissions

**Comment by drizzle-mizzle** [comment]
Do both bots actually launch? Does it have any errors in console logs?

**Comment by drizzle-mizzle** [comment]
No matter how much bots you will launch, they won't affect each others work. You have to make sure you did not mess up something with bots' working folders or config files.

**Comment by drizzle-mizzle** [comment]
Added a little build guide here: https://github.com/drizzle-mizzle/CharacterAI-Discord-Bot/wiki/Build-youself
