### ISSUE TITLE
character.ai  page not opening

### ISSUE THREAD

**Issue by KalebelyNOT1** [drizzle-mizzle/CharacterAI-Discord-Bot#115]
![code](https://github.com/drizzle-mizzle/CharacterAI-Discord-Bot/assets/136034536/f611e53e-1364-4604-a649-2a4a945850b9)

This happens when I run CharacterAI_Discord_Bot.exe I've done all the instructions and even tried deleting and re installing the windows zip file.

**Comment by drizzle-mizzle** [comment]
Did you check if site was actually available on this time?

**Comment by drizzle-mizzle** [comment]
Maybe there was some maintenance going on, or you had problems with your connection.
Try again.
