### ISSUE TITLE
[BUG] Something went wrong...

### ISSUE THREAD

**Issue by MeeIIs635** [drizzle-mizzle/CharacterAI-Discord-Bot#118]
- [x] I am using the [latest version](https://github.com/drizzle-mizzle/CharacterAI-Discord-Bot/releases/latest) of the program.
- [x] I have read the [Known-issues](https://github.com/drizzle-mizzle/CharacterAI-Discord-Bot#known-issues) section and [Issues](https://github.com/drizzle-mizzle/CharacterAI-Discord-Bot/issues) page and made sure that this problem was not already described elsewhere.

### Describe the bug:
When opening the executable CharacterAI_Discord_Bot it crashes. Check my Config.json to see if anything's wrong

### Steps to reproduce the behaviour:
1. Execute CharacterAI_Discord_Bot
2. Do nothing

### Expected behaviour:
Starts setup, but doesn't

### Screenshots:
Screenshots below

### Additional info:
- My OS is Windows 11
- ...
![image](https://github.com/drizzle-mizzle/CharacterAI-Discord-Bot/assets/86620152/1f4204e5-08a4-4983-bafe-2270ff912364)
![image](https://github.com/drizzle-mizzle/CharacterAI-Discord-Bot/assets/86620152/5dd23bdc-10a4-4157-8500-322959fcd52f)

**Comment by drizzle-mizzle** [comment]
link in the end must be `"quoted"`

**Comment by drizzle-mizzle** [comment]
id is id, not a link


![image](https://github.com/drizzle-mizzle/CharacterAI-Discord-Bot/assets/55811932/fd576b90-0c56-451b-a5c4-5a325207c1a8)

**Comment by drizzle-mizzle** [comment]
like this

![image](https://github.com/drizzle-mizzle/CharacterAI-Discord-Bot/assets/55811932/1055bc94-0e7a-4814-bf13-e1a9f7abb990)

**Comment by drizzle-mizzle** [comment]
> > link in the end must be `"quoted"`
> 
> what do you mean by that? that the id is id not a link? or is this another thing i did wrong?

I deleted that message. I just saw a link without quotes (each and every text string in JSON file should be "quoted") and decided that it is the problem, and only then realized it should not be there at all.
