### ISSUE TITLE
Seem to be failing to connect to character.ai

### ISSUE THREAD

**Issue by Disgustiosa** [drizzle-mizzle/CharacterAI-Discord-Bot#12]
![image](https://user-images.githubusercontent.com/122424571/212502609-e8002ce8-0b86-4d16-8a4e-278273766d0c.png)
Hi. I have triple checked that my user token is correct but am still somehow having this issue. Would be helpful if the error message from character.ai was printed as it might help me figure out the problem. Is this still working for anyone else? I worry the char ai devs might have broken something.

I am on Windows. I have tried running as administrator and making exceptions in the firewall for the program, still nothing.

**Comment by Disgustiosa** [comment]
Nevermind, I accidentally copied the access token instead of the key... Of course I didn't notice until after opening the issue. Thank you, this is kickass!

**Comment by drizzle-mizzle** [comment]
But you're right, gotta add error description to a failure logs
