### ISSUE TITLE
[Feature request]

### ISSUE THREAD

**Issue by OmegaBF** [drizzle-mizzle/CharacterAI-Discord-Bot#120]
remove the filter

**Comment by Mj83621** [comment]
Dude, if your trying to remove the filter, you cant use c.ai, you could use something chai or replika. if your really trying to use c.ai, use the mobile app of it, i know it isnt on discord, but its weaker for some reason. i checked.

**Comment by drizzle-mizzle** [comment]
> remove the filter

Beg me.

**Comment by justkorudev** [comment]
> remove the filter

No. If you want to use AI for nsfw, please check your mental health.

**Comment by drizzle-mizzle** [comment]
I don't really think he should. SFW or NSFW, it's just the definition of range of communication capabilities AI can, and better to, have, and these are for sure way too over-limited on cAI, in not really sane measure.

**Comment by drizzle-mizzle** [comment]
Also, this is not a reddit. So, please, restrain from *expressions* like that, even toward ones like this ridiculous issue's authors.
