### ISSUE TITLE
[Help] maybe I just stupid but I cant set up a character saying I have no power

### ISSUE THREAD

**Issue by Ryukkia** [drizzle-mizzle/CharacterAI-Discord-Bot#122]
- [x] I am using the [latest version](https://github.com/drizzle-mizzle/CharacterAI-Discord-Bot/releases/latest) of the program.
- [ ] I have tried to [google](https://www.google.com/webhp) my problem or made sure it can not be solver with it.
- [ ] I have read the [How-to-set-up](https://github.com/drizzle-mizzle/CharacterAI-Discord-Bot/wiki/How-to-set-up) page completely and made sure that there is no answer to my question.
- [ ] I have read the [Additional-configuration](https://github.com/drizzle-mizzle/CharacterAI-Discord-Bot/wiki/Additional-configuration) page completely and made sure that there is no answer to my question.
- [ ] I have read the [Important-Notes](https://github.com/drizzle-mizzle/CharacterAI-Discord-Bot/wiki/Important-Notes) page completely and made sure that there is no answer to my question.
- [ ] I have read the [Commands](https://github.com/drizzle-mizzle/CharacterAI-Discord-Bot/wiki/Commands) page completely and made sure that there is no answer to my question.

### Problem description:
...

### What I have tried to do to solve my problem:
...

### Additional info:
- My OS:
- ...

**Comment by drizzle-mizzle** [comment]
dude, these things are here for a reason, you know?
![image](https://github.com/drizzle-mizzle/CharacterAI-Discord-Bot/assets/55811932/42343a06-4257-403a-a3d2-a647ef96d527)

**Comment by drizzle-mizzle** [comment]
https://github.com/drizzle-mizzle/CharacterAI-Discord-Bot/issues?q=no+power
