### ISSUE TITLE
Docker container throttles CPU and spams logs.

### ISSUE THREAD

**Issue by shinysocks** [drizzle-mizzle/CharacterAI-Discord-Bot#124]
- [x] I am using the [latest version](https://github.com/drizzle-mizzle/CharacterAI-Discord-Bot/releases/latest) of the program.
- [x] I have read the [Known-issues](https://github.com/drizzle-mizzle/CharacterAI-Discord-Bot#known-issues) section and [Issues](https://github.com/drizzle-mizzle/CharacterAI-Discord-Bot/issues) page, and made sure that this problem was not already described elsewhere.

### Describe the bug:
The docker container works but spams logs with `#` and uses way too much of the CPU...

### Steps to reproduce the behavior:
1. Clone repo
2. Run docker container

### Expected behavior:
Container should have a similar performance impact as when run outside of container and shouldn't spam logs.

### Screenshots:
Output of running `docker logs -tf container_name`:
![image](https://github.com/drizzle-mizzle/CharacterAI-Discord-Bot/assets/91911303/143d03fc-940a-4a41-bf97-18b1a1380234)

**Comment by drizzle-mizzle** [comment]
I'm not familiar with docker enough to come with any guess why it behaves like this.

**Comment by drizzle-mizzle** [comment]
Has something to do with how it handles the console user input. There's a block in the code that outputs `#` and awaits for a user input. For now, you can simply delete it (it's in the `Program.cs` file), and that spam will go away. No idea if that is the reason of performance problems though

**Comment by drizzle-mizzle** [comment]
> Maybe make a docker branch with those lines removed for anyone else who wants to use docker? Up to you.

Removed that shit completely
