### ISSUE TITLE
[Help] how do I use this on Mac

### ISSUE THREAD

**Issue by Operix** [drizzle-mizzle/CharacterAI-Discord-Bot#130]
- [x] I am using the [latest version](https://github.com/drizzle-mizzle/CharacterAI-Discord-Bot/releases/latest) of the program.
- [ ] I have tried to [google](https://www.google.com/webhp) my problem or made sure it can not be solver with it.
- [x] I have read the [How-to-set-up](https://github.com/drizzle-mizzle/CharacterAI-Discord-Bot/wiki/How-to-set-up) page completely and made sure that there is no answer to my question.
- [x] I have read the [Additional-configuration](https://github.com/drizzle-mizzle/CharacterAI-Discord-Bot/wiki/Additional-configuration) page completely and made sure that there is no answer to my question.
- [x] I have read the [Important-Notes](https://github.com/drizzle-mizzle/CharacterAI-Discord-Bot/wiki/Important-Notes) page completely and made sure that there is no answer to my question.
- [x] I have read the [Commands](https://github.com/drizzle-mizzle/CharacterAI-Discord-Bot/wiki/Commands) page completely and made sure that there is no answer to my question.

### Problem description:
how tf do I run this on a MacOs

### What I have tried to do to solve my problem:
- changed file to .exe
- changed file to .py
- filed an issue

### Additional info:
- My OS: MacosX
- using python3
- winebottler does not work

**Comment by drizzle-mizzle** [comment]
> changed file to .exe

Why would you think windows `.exe` would work on your mac...

> changed file to .py

Why would you think Python has anything to do with it...

> using python3

What does it mean...

On macOS, you actually need to follow same steps as on Linux, but you will have to figure out by yourself how to install dependencies. I don't have mac, so you're on your own with the google here.
