### ISSUE TITLE
"You have no power here"

### ISSUE THREAD

**Issue by spongebobspongebob666** [drizzle-mizzle/CharacterAI-Discord-Bot#131]
Did everything as intended, but as soon as I type ".ai set [bot]" I get a response gif with the "You have no power here" thing...
![image](https://github.com/drizzle-mizzle/CharacterAI-Discord-Bot/assets/138666608/0529bd55-6a96-424f-8600-f0608f91b922)
![image](https://github.com/drizzle-mizzle/CharacterAI-Discord-Bot/assets/138666608/b811b413-4a40-4472-8177-25943835f938)

Things run perfectly, though.

**Comment by Axislmao** [comment]
set a role in "discord_bot_role": "   here    ", in the config and give that role to yourself in the server (i had the same issue and thats how it was fixed)
