### ISSUE TITLE
2-for-1 feature suggestion

### ISSUE THREAD

**Issue by DeroPlayz** [drizzle-mizzle/CharacterAI-Discord-Bot#133]
So I'm on the latest version of this, and it works very well. There's just two small things (technically 3). having to ping in server channels for replies is kinda annoying, I wish it could just analyze whether a message is directed towards it, but not a big deal, but being able to hunt a role would be nice, especially as a potential punishment for rule breakers, lol.

Also, I don't know how possible this is, and don't want to come across like a dick, but it'd be cool if the bot could get server info, like the member list and channel list/names, member roles, etc. Just allows the bot to be more immersive, but I understand not adding it/it not being doable (:)

**Comment by drizzle-mizzle** [comment]
> I wish it could just analyze whether a message is directed towards it

It's a language model, not some conscious ai processor, it's impossible

> but being able to hunt a role would be nice

Maybe later

> but it'd be cool if the bot could get server info, like the member list and channel list/names, member roles, etc

You can tell about stuff like this to the bot in the form of a *"system message"*, but it would be meaningless, as cAI has very short and limited memory.

**Comment by DeroPlayz** [comment]
True, I guess it could be declared in example dialogue
