### ISSUE TITLE
bot doesn't set characters

### ISSUE THREAD

**Issue by g00seisint0wn** [drizzle-mizzle/CharacterAI-Discord-Bot#134]
- [x] I am using the [latest version](https://github.com/drizzle-mizzle/CharacterAI-Discord-Bot/releases/latest) of the program.
- [x] I have tried to [google](https://www.google.com/webhp) my problem or made sure it can not be solver with it.
- [x] I have read the [How-to-set-up](https://github.com/drizzle-mizzle/CharacterAI-Discord-Bot/wiki/How-to-set-up) page completely and made sure that there is no answer to my question.
- [x] I have read the [Additional-configuration](https://github.com/drizzle-mizzle/CharacterAI-Discord-Bot/wiki/Additional-configuration) page completely and made sure that there is no answer to my question.
- [x] I have read the [Important-Notes](https://github.com/drizzle-mizzle/CharacterAI-Discord-Bot/wiki/Important-Notes) page completely and made sure that there is no answer to my question.
- [x] I have read the [Commands](https://github.com/drizzle-mizzle/CharacterAI-Discord-Bot/wiki/Commands) page completely and made sure that there is no answer to my question.

### Problem description:
when I try to run the bot command (.ai set) it just says "set a character first"  when I already have?
I tried finding the character by its name and the ID but neither worked!

### Screenshots:
![Screenshot 2023-07-08 12 48 08 AM](https://github.com/drizzle-mizzle/CharacterAI-Discord-Bot/assets/138736977/3c208c06-23ac-4a41-9875-30c99aaf26d2)

### What I have tried to do to solve my problem:
tried redoing the bot, asking a friend for help, and googling

### Additional info:
- My OS: ChromeOS

**Comment by xXG0DLessXx** [comment]
Did you read the update notes..? In the latest version of the bot you also need to put a “#” right in front of the command for it to be recognized as a command.

**Comment by g00seisint0wn** [comment]
OHHH! tysm! i actually didn't notice that

thank yooou :D
