### ISSUE TITLE
Feature Request: Multi channels

### ISSUE THREAD

**Issue by justkorudev** [drizzle-mizzle/CharacterAI-Discord-Bot#14]
Could you add a way in which depending on the channel you talk the bot to it saves it as a different conversation? For example to make private channelswhere users can talk with the bot but the bot won't tell anyone outside that channel what they were talking about. This would be great for the amode.
Something like "User [User] in channel [Channel] says:"

**Comment by justkorudev** [comment]
Could you tell us if you will do this and an ETA? Thanks.

**Comment by drizzle-mizzle** [comment]
Good idea, I'll try it this week.
But to change audience mode format would be absolutely unnecessary, it will only confuse AI, I'll just use different history_external_id(s)

**Comment by justkorudev** [comment]
ok! that will be amazing!

**Comment by justkorudev** [comment]
Tell me when you add it please

**Comment by drizzle-mizzle** [comment]
Sorry for keep you waiting that long (I had **really** much stuff to do IRL)
Here it is: #21

**Comment by drizzle-mizzle** [comment]
@justkorudev
Sorry for keep you waiting that long (I had **really** much stuff to do IRL)
## Here it is: #21

**Comment by justkorudev** [comment]
Thanks a lot!
