### ISSUE TITLE
[BUG] Translating stuck

### ISSUE THREAD

**Issue by MeeIIs635** [drizzle-mizzle/CharacterAI-Discord-Bot#142]
- [x] I have read the [Known-issues](https://github.com/drizzle-mizzle/CharacterAI-Discord-Bot#known-issues) section and [Issues](https://github.com/drizzle-mizzle/CharacterAI-Discord-Bot/issues) page, and made sure that this problem was not already described elsewhere.

### Describe the bug:
When I press "abc" on reactions to it's message (translate) it stays on (Wait...) forever. I'm not sure if this has something to do with the API. I don't know what an API token is, if that's what I'm supposed to put, but I just put the long code.

### Steps to reproduce the behavior:
1. Go to Config
2. Set translate button to true and enter API

### Expected behavior:
Translates the message

### Screenshots:
Screenshots attached

### Additional info:
- My OS is Windows 11
![image](https://github.com/drizzle-mizzle/CharacterAI-Discord-Bot/assets/86620152/c8d2a966-7f14-4cd1-9fc0-a792b7e20340)
- I am not using the latest version of the program. How would I update without having to redo all the configuration?

**Comment by drizzle-mizzle** [comment]
> I'm not sure if this has something to do with the API. I don't know what an API token is, if that's what I'm supposed to put, but I just put the long code

Did you follow these instructions?
https://github.com/drizzle-mizzle/CharacterAI-Discord-Bot/wiki/Additional-configuration#set-enable_translate_button-to-true-and-specify-deepl_api_token-with-your-deepl-api-token-if-you-want-to-use-embedded-messages-translator
![image](https://github.com/drizzle-mizzle/CharacterAI-Discord-Bot/assets/55811932/0b74babf-589a-4aa7-b269-bf3dfdd45edf)

> How would I update without having to redo all the configuration?

There's not much things you have to change, just refill all needed data in the config file.
