### ISSUE TITLE
[Help] Application closes down

### ISSUE THREAD

**Issue by julientel** [drizzle-mizzle/CharacterAI-Discord-Bot#145]
I've been using your bot for almost a month now but all of a sudden it just stopped launching. 
When I run the application, it says this:

![image](https://github.com/drizzle-mizzle/CharacterAI-Discord-Bot/assets/140942686/6d125492-ba4e-448f-8a1e-8630054f3e25)

and then just closes down. I'm new to coding, so I can't really figure out what's wrong.

**Comment by drizzle-mizzle** [comment]
Looks like you have deleted a dll file from the app catalog.

**Comment by carseatheadresting** [comment]
i had the same problem, how do i fix this?

**Comment by drizzle-mizzle** [comment]
@carseatheadresting just... don't delete files from the bot catalog...
