### ISSUE TITLE
[Help]

### ISSUE THREAD

**Issue by Mukun21** [drizzle-mizzle/CharacterAI-Discord-Bot#149]
It's confusing for a non developer. Could you please add a video tutorial of how to set up and add the bot on Discord in windows 10?

**Comment by Mj83621** [comment]
I don’t think he’ll make a video, but I can walk you through it, and its not even THAT confusing

**Comment by Mj83621** [comment]
you could also switch the the [character engine](https://github.com/drizzle-mizzle/Character-Engine-Discord), which doesnt require any set up, can hold up to 15 characters in one channel, and supports Character hub.

**Comment by Mj83621** [comment]
(by no set up i mean join the discord and add the bot to your server, shouldve clarified that)

**Comment by Mukun21** [comment]
> (by no set up i mean join the discord and add the bot to your server, shouldve clarified that)

I need a little help with setup. My windows says "Windows cannot find the file in the system". Maybe I'm doing something wrong. If you want you can join this testing server https://discord.com/invite/T65MmTep
