### ISSUE TITLE
Feature request: more settings

### ISSUE THREAD

**Issue by DdaannnRU** [drizzle-mizzle/CharacterAI-Discord-Bot#18]
More specifficly i would like to disable "in response to" message. It breaks my character.
And also options to set bot's activity, status, and author mention in reply(idk how to do it here, but in discord.py it's await ctx.reply("text", mention_author=False)).

**Comment by DdaannnRU** [comment]
Under status i meant online, dnd etc. 
I use this project with some of my own code on python, so yes, i would like to change that.
I would like to leave user nicknames in amode, but disable "in response to" message, only this part of amode breaks my character.

**Comment by NekoraNeko** [comment]
ability to change play activity field is useful~

**Comment by drizzle-mizzle** [comment]
@DdaannnRU @NekoraNeko 
- **Added in #21**
