### ISSUE TITLE
[BUG] New version is broken... at least for me

### ISSUE THREAD

**Issue by K0shachiyamyatA** [drizzle-mizzle/CharacterAI-Discord-Bot#23]
Bot doesn't reply in discord.
![Screenshot_20230220_105822_AnyDesk](https://user-images.githubusercontent.com/88767403/220035336-17abbbab-125a-43e9-a9a9-9abcc4ca4103.jpg)
![Screenshot_20230220_110012_Bluecord Beta](https://user-images.githubusercontent.com/88767403/220035345-20a5bec0-55d4-48ab-8098-78ae38b86f50.jpg)

**Comment by drizzle-mizzle** [comment]
@K0shachiyamyatA использовал auto_setup?

**Comment by K0shachiyamyatA** [comment]
> @K0shachiyamyatA использовал auto_setup?

Да, использовал. По консоли же видно всё. Там в gateway какое-то сообщение. Мб оно здесь виновато?

**Comment by drizzle-mizzle** [comment]
В консоли будет ровно то же само, если запустить без авто и добавить вручную.
Проблема именно в этом, да. Я в последнем обновлении добавил разделение историй по каналам, а авто настройка происходит вне контекста какого-либо канала, потому он не подхватывается. Нужно принудительно выполнить `reset` или `set/find` в нужном канале. При следующем запуске канал уже будет сохранён в табличку в /storage/, и всё будет нормально. Сейчас добавлю это в ридми.
Пока перекачай [1.81](https://github.com/drizzle-mizzle/CharacterAI-Discord-Bot/releases/tag/bugfix_1.81), там другой баг поправил

**Comment by K0shachiyamyatA** [comment]
Хорошо, спасибо. 

> В консоли будет ровно то же само, если запустить без авто и добавить вручную. Проблема именно в этом, да (в авто настройке, не сообщении). Я в последнем обновлении добавил разделение историй по каналам, а авто настройка происходит вне контекста какого-либо канала, потому он не подхватывается. Нужно принудительно выполнить `reset` или `set/find` в нужном канале. При следующем запуске канал уже будет сохранён в табличку в /storage/, и всё будет нормально. Сейчас добавлю это в ридми. Пока перекачай [1.81](https://github.com/drizzle-mizzle/CharacterAI-Discord-Bot/releases/tag/bugfix_1.81), там другой баг поправил

**Comment by K0shachiyamyatA** [comment]
> В консоли будет ровно то же само, если запустить без авто и добавить вручную. Проблема именно в этом, да (в авто настройке, не сообщении). Я в последнем обновлении добавил разделение историй по каналам, а авто настройка происходит вне контекста какого-либо канала, потому он не подхватывается. Нужно принудительно выполнить `reset` или `set/find` в нужном канале. При следующем запуске канал уже будет сохранён в табличку в /storage/, и всё будет нормально. Сейчас добавлю это в ридми. Пока перекачай [1.81](https://github.com/drizzle-mizzle/CharacterAI-Discord-Bot/releases/tag/bugfix_1.81), там другой баг поправил

Кстати, раз уж заговорили на великом и могучем:
-я просил еще возможность менять статусы бота по типу онлайн, dnd(do not disturb) и тд.
-и если не сделано, то еще возможность отключить пинг юзера в реплае. 
Может если бы умел C# сам юзать, то самому для себя проще сделать было. Но я только функции C в колледже проходить начал) а с питоном я пытался для себя через selenium сделать, но cloudflare детектит собака)

**Comment by drizzle-mizzle** [comment]
Уже добавил, ищи в списке команд в самом низу.
Под пингом имеешь ввиду ссылку на предыдущее сообщение? Если именно пинг через @, то он есть только при выполнении `set`\`find`. Если ссылку, то не понимаю зачем. Без неё нереально разобраться, кому и что ответил персонаж, когда с ним общаются хотя бы два человека

**Comment by K0shachiyamyatA** [comment]
> Уже добавил, ищи в списке команд в самом низу. Под пингом имеешь ввиду ссылку на предыдущее сообщение? Если именно пинг через @, то он есть только при выполнении `set``find`. Если ссылку, то не понимаю зачем. Без неё нереально разобраться, кому и что ответил персонаж, когда с ним общаются хотя бы два человека

Нет, смотри, ссылка на приложения остаться должна. Но в discord.py есть такой аргумент у ctx.reply, называется "mention_author" и в состоянии False он выключает пинг юзера при ссылке на его сообщение. Я не знаю деталей, мб в C# и нет такого, но как факт.

**Comment by drizzle-mizzle** [comment]
Так пинга и так нет же, только ссылка🤔

**Comment by K0shachiyamyatA** [comment]
> Так пинга и так нет же, только ссылка🤔

![Uploading Screenshot_20230220_124445_Bluecord Beta.jpg…]()

**Comment by K0shachiyamyatA** [comment]
> Так пинга и так нет же, только ссылка🤔

![Screenshot_20230220_124445_Bluecord Beta](https://user-images.githubusercontent.com/88767403/220056157-d3094a4e-dece-4cb4-b8c6-cfc945770975.jpg)

**Comment by drizzle-mizzle** [comment]
А, ты про это. Понял.
Потом сделаю, не сегодня.

**Comment by K0shachiyamyatA** [comment]
Хорошо, главное чтобы было)

> А, ты про это. Понял. Потом сделаю, не сегодня.
