### ISSUE TITLE
Amode and some other commands broke

### ISSUE THREAD

**Issue by justkorudev** [drizzle-mizzle/CharacterAI-Discord-Bot#25]
Basically both amode and help return ⚠ The input text has too few parameters., BadArgCount.

**Comment by justkorudev** [comment]
And amode toggle *number* returns ⚠ Failed to parse Int32., ParseFailed and audience toggle 3 doesn't answer

**Comment by justkorudev** [comment]
Enabling audience mode by default in config works

**Comment by drizzle-mizzle** [comment]
Are you sure you have not misspelled something?
![image](https://user-images.githubusercontent.com/55811932/220211921-3d902be5-8481-4a1f-8ae0-ed171ddc78ac.png)
![image](https://user-images.githubusercontent.com/55811932/220212080-378da9d4-8b4d-4a27-97d4-7b9539baad25.png)

**Comment by drizzle-mizzle** [comment]
But I really have to add page 1 as default one in `help`

**Comment by justkorudev** [comment]
Now it just doesn’t answer my queries

**Comment by justkorudev** [comment]
> But I really have to add page 1 as default one in `help`

Yeah

**Comment by justkorudev** [comment]
![7BC9E8AE-932E-4818-8273-9BBE7225B1C8](https://user-images.githubusercontent.com/44905402/220289392-36964bf6-ebfd-416a-80dc-9c5a4f230bb3.jpeg)

**Comment by justkorudev** [comment]
Just no answer

**Comment by justkorudev** [comment]
Maybe it's because of enabling amode in config? I feel there should be more error messages

**Comment by drizzle-mizzle** [comment]
I guess, you're using auto setup. Check out the bottom of this page: [Additional configuration] (https://github.com/drizzle-mizzle/CharacterAI-Discord-Bot/wiki/Additional-configuration)

**Comment by drizzle-mizzle** [comment]
But I don't remember if amode is actually affected by this. I'll check it when I'm home

**Comment by drizzle-mizzle** [comment]
The reason is that now every channel has it's own history and it's own audience mode. But when you run bot with auto setup with some character for the first time, it have no channels in it's storage. That's why you'll need to call 'reset'. But if you'll turn the bot off and later launch it with auto setup and with same character, it will find it's history and will work as expected

**Comment by drizzle-mizzle** [comment]
I'll have to modernize it a little too

**Comment by drizzle-mizzle** [comment]
Probably, gotta set some history_id as default one, so you would not need to call reset for every channel

**Comment by justkorudev** [comment]
> I guess, you're using auto setup. Check out the bottom of this page: [Additional configuration](https://github.com/drizzle-mizzle/CharacterAI-Discord-Bot/wiki/Additional-configuration)

No no auto setup

**Comment by justkorudev** [comment]
> Probably, gotta set some history_id as default one, so you would not need to call reset for every 

yeah

**Comment by justkorudev** [comment]
> Either you set character in one channel and tried to call in another one

That’s probably what happened.

**Comment by drizzle-mizzle** [comment]
- Fixed in [1.82](https://github.com/drizzle-mizzle/CharacterAI-Discord-Bot/releases/tag/1.82)
