### ISSUE TITLE
Feature request: Custom Private Category Names

### ISSUE THREAD

**Issue by justkorudev** [drizzle-mizzle/CharacterAI-Discord-Bot#26]
Add a way for us to change the category name for private channels

**Comment by justkorudev** [comment]
I hope to see this here soon, in my semi public server I really need it

**Comment by justkorudev** [comment]
> I'll update it on this week

Cool

**Comment by drizzle-mizzle** [comment]
- Added in [1.82](https://github.com/drizzle-mizzle/CharacterAI-Discord-Bot/releases/tag/1.82)
