### ISSUE TITLE
Feature: dm's and @mention toggle

### ISSUE THREAD

**Issue by JcynR** [drizzle-mizzle/CharacterAI-Discord-Bot#29]
Since you just added private channels, I was wondering if you could add a way to write messages directly to the bot instead of only via a channel.

And also consider adding a option to disable @mentioning the user when it's just a 1 on 1 conversation. This would make the conversation more realistic, @mentioning isn't always neccessary.

**Comment by justkorudev** [comment]
You can enable always answering a user with the command *hunt*

**Comment by drizzle-mizzle** [comment]
> Since you just added private channels, I was wondering if you could add a way to write messages directly to the bot instead of only via a channel.
I'm not sure if I correctly understand what you actually mean.
> This would make the conversation more realistic, @mentioning isn't always neccessary.
You can simply reply on bot's messages with reply button. Or, as mentioned above, use hunt on yourself.

**Comment by JcynR** [comment]
Right click the bot and click on Message, it will take you to a DM window. Wouldn't it be nice if you could start a conversation through there also instead of only via a discord server?

At the same time you can disable the @user in the bot's messages so you don't see this yellow box constantly in the messages. There is no need for the bot to mention the user when it's having a 1 on 1 conversation with you in a private channel or DM unless other parties are around.

**Comment by drizzle-mizzle** [comment]
- Added in [1.82](https://github.com/drizzle-mizzle/CharacterAI-Discord-Bot/releases/tag/1.82)
