### ISSUE TITLE
Feature: Show a different help depending on the user's permissions

### ISSUE THREAD

**Issue by justkorudev** [drizzle-mizzle/CharacterAI-Discord-Bot#33]

**Comment by justkorudev** [comment]
I need it please

**Comment by justkorudev** [comment]
I don't want my normal users to see admin commands

**Comment by drizzle-mizzle** [comment]
- Added in [1.83](https://github.com/drizzle-mizzle/CharacterAI-Discord-Bot/releases/tag/1.83)
