### ISSUE TITLE
Audience mode for channels

### ISSUE THREAD

**Issue by UnconsciousPebble** [drizzle-mizzle/CharacterAI-Discord-Bot#34]
Allow a way for the bot to differentiate different channels for context in a similar way it is made to differentiate between users to allow different context. For example this could be used for roleplay channels with a corresponding channel name.

**Comment by drizzle-mizzle** [comment]
If I correctly understand what you mean – it is already implemented. By default, every channel uses first initialized chat (history id) with a character, the one that's found or created when you use auto setup or set/find command. Separate history created only when you use `private` command, or if you `reset` bot in needed channel.
Gotta add it to the guide.

**Comment by drizzle-mizzle** [comment]
- [Check it out](https://github.com/drizzle-mizzle/CharacterAI-Discord-Bot/wiki/Important-notes)
