### ISSUE TITLE
Allow to add multiple characters

### ISSUE THREAD

**Issue by UnconsciousPebble** [drizzle-mizzle/CharacterAI-Discord-Bot#36]
Would it be possible to allow the bot to use multiple character-ids in one installation?
For example, other than the default character "A" the bot would reply as when pinged, users could be able to talk to other registered characters, by mentioning their message with "@botname-characterB", in this case the bot would reply using the other's characters name and profile picture.

**Comment by drizzle-mizzle** [comment]
Nope.
1) It's way too complicated to implement and actually use on practice.
2) It would look ludicrously bad and ugly.
3) You can't spam Discord with changing profile info request so fast.
4) You can simply set two bots...

**Comment by MeeIIs635** [comment]
> Nope.
> 
> 1. It's way too complicated to implement and actually use on practice.
> 2. It would look ludicrously bad and ugly.
> 3. You can't spam Discord with changing profile info request so fast.
> 4. You can simply set two bots...

How would I go about making two bots?
