### ISSUE TITLE
Suggestion: Add updating stats/status indicators for the bot

### ISSUE THREAD

**Issue by UnconsciousPebble** [drizzle-mizzle/CharacterAI-Discord-Bot#37]
Would it be possible to add periodically updating stats on current usage (number of total/per day/per hour replies by the bot) and maybe an uptime status (how long is has been online since the last interruption) and a confirmation it is online again after a hibernation/standby state of the host computer to the console or alternatively in the form of a Discord command?

**Comment by drizzle-mizzle** [comment]
> Would it be possible to add periodically updating stats on current usage (number of total/per day/per hour replies by the bot)
Why would anyone need it... I really can't see any usage of it.

> an uptime status (how long is has been online since the last interruption)
You, as a hoster, can see it in logs. And, again, I don't understand why would anyone need it.
When you make some odd requests like this, please, provide at least any reason why it worth to implement it.

**Comment by UnconsciousPebble** [comment]
> Why would anyone need it... I really can't see any usage of it.
This one just for statistic purposes.

> You, as a hoster, can see it in logs
Where can I see it?
The main reason why I requested that is, because there is no confirmation of any kind whether the bot has reconnected successfully after the hosting desktop woke up from standby mode.
