### ISSUE TITLE
Issue: Audience mode no longer works in servers

### ISSUE THREAD

**Issue by Huskydude422** [drizzle-mizzle/CharacterAI-Discord-Bot#40]
I'm getting this error now, downgrading to the previous version fixes it.

⚠ Failed to execute command: Failed to parse Int32. (ParseFailed)

**Comment by Huskydude422** [comment]
This is with the windows client by the way, sorry i forgot to menion

**Comment by drizzle-mizzle** [comment]
Please, read documentation before create an issue. Some commands may change it's behavior with new updates. Audience mode command has parameters now.
https://github.com/drizzle-mizzle/CharacterAI-Discord-Bot/wiki/Commands
