### ISSUE TITLE
wls Ubuntu problem...

### ISSUE THREAD

**Issue by HurryUpy** [drizzle-mizzle/CharacterAI-Discord-Bot#41]
please help me. I haven't used linux before, and I don't know anything except basic things. So, in Ubuntu, when I enter chmod 777 ./CharacterAI_Discord_Bot, I get No such file or directory. I tried to solve this problem, but what I found did not give much explanation. I 
didn't know where to turn, so I'm writing here

**Comment by drizzle-mizzle** [comment]
> I tried to solve this problem
It doesn't seem like you did.
> but what I found did not give much explanation
Explanation is in error itself. There's no such file as `CharacterAI_Discord_Bot`. Which means you're not in application directory.
My friend, I don't mind to help people with silly things like that, but before you come here and create an absolute off-topic issue, you can at least try to think what problem is actually about, I'm not a Google! 
Here's what you do:
0) Redownload [Application](https://github.com/drizzle-mizzle/CharacterAI-Discord-Bot/releases/latest) , as there was a minor update today.
1) In Windows, unzip bot archive in any convenient directory. I'll use `C:\` root directory for axample.
2) Go to Ubuntu. Execute `sudo apt update && sudo apt upgrade`, just in case.
3) Move to the bot directory: `cd /mnt/c/cAI-Discord-Linux-x64` - `/mnt/c/` stands for C volume as a mounted drive.
3) Execute `sudo chmod 777 CharacterAI_Discord_Bot` - CharacterAI_Discord_Bot is an application executable binary file
4) Launch it `./CharacterAI_Discord_Bot`
