### ISSUE TITLE
Increased anti-bot security from c.AI

### ISSUE THREAD

**Issue by hyper-neutrino** [drizzle-mizzle/CharacterAI-Discord-Bot#44]
Following last night's maintenance, bots have started responding with "Sorry, character.ai has increased its securitry against bots. This feature will be unavailable indefinitely."

Will this project be updated to get around this or should c.AI-discord users just find alternative options?

Thanks.

**Comment by unethicalwhitehat** [comment]
I tried to install and use this today however despite using Ubuntu VIA WSL and ExpressVPN, I continue to get the "Response: Forbidden" error message.,

**Comment by drizzle-mizzle** [comment]
> I tried to install and use this today however despite using Ubuntu VIA WSL and ExpressVPN, I continue to get the "Response: Forbidden" error message.,

#43
