### ISSUE TITLE
Bot doesn't do anything

### ISSUE THREAD

**Issue by ProfaneServitor** [drizzle-mizzle/CharacterAI-Discord-Bot#52]
The bot fails to generate any messages. Logs don't generate any errors.

```bash
22:33:52 Discord     Discord.Net v3.9.0 (API v10)
22:33:52 Gateway     Connecting
22:33:54 Gateway     You're using the GuildPresences intent without listening to the PresenceUpdate event, consider removing the intent from your config.
22:33:54 Gateway     Connected
22:33:54 Gateway     Ready

Launching browser...
It may take some time on the first launch, because it will need to download a Chrome executable (~450mb).
If this process takes too much time, ensure you have good internet connection (timeout = 15 minutes).

Starting character setup...
  (Character ID: kZYuFos9LPhFFwGt3EAW9Zpqzx_vu3DCxNgwHhT68EQ)
Fetching character info... 
Starting character setup...
  (Character ID: mMgy5BxyDsna4kdEAXgZqaprq8mRF6Mx04rfhlb5WPs)
Fetching character info... 
Starting character setup...
  (Character ID: mMgy5BxyDsna4kdEAXgZqaprq8mRF6Mx04rfhlb5WPs)
Fetching character info...
```

Is there a way to generate more verbose response to see what is wrong?

## Notes
I live in Crimea, but the site itself works fine here. Besides, the issue persists while launching with VPN.

**Comment by deonthewall** [comment]
Getting the same thing, except I finally got an error message after waiting for ~40 mins

**Comment by drizzle-mizzle** [comment]
Try [this](https://github.com/drizzle-mizzle/CharacterAI-Discord-Bot/issues/43#issuecomment-1493057316) for now, if you host it on PC with gui. If you don't, just try to relaunch the whole app for free times.
I'll try to fix it on weekends.

**Comment by drizzle-mizzle** [comment]
> Getting the same thing, except I finally got an error message after waiting for ~40 mins ![image]

I found a problem sourse. It will be fixed on this week. 
For now, just try to use `auto_setup` in config.
