### ISSUE TITLE
Is it possible to change history id?

### ISSUE THREAD

**Issue by oogtoog** [drizzle-mizzle/CharacterAI-Discord-Bot#59]
I "lost" a conversation I had in private DMs when I had to close the .exe at one point. I wanted to go back to that same convo but it always starts a new one when I restart the .exe and set the character.

**Comment by drizzle-mizzle** [comment]
It's not, but I'll implement it soon.

**Comment by drizzle-mizzle** [comment]
> I "lost" a conversation I had in private DMs when I had to close the .exe at one point. I wanted to go back to that same convo but it always starts a new one when I restart the .exe and set the character.

But for now, you can do this:
1. Go to cAI site
2. Find this history in "chats"
3. Write one message there
4. Go to discord, change character with command, change it back to previous one – it will drop local histories and will load a last one

**Comment by oogtoog** [comment]
I tried to get this to work several times, following the steps faithfully, but no success
I went to the cAI site, revived the old conversation with a message so that it's active, went on discord and changed the character to a different one, then changed it back to the original one, and it always starts a new convo with its greeting. It refuses to "pick up" the active conversation on cAI.
Must be something wrong on my end, on what I'm doing..
But it's alright, thanks, I'll wait for the implementation.

**Comment by oogtoog** [comment]
Yes I thought so, but when I respond to it.. it stays as a new chat. I check on the cAI site, and find my message that I sent on discord on the new chat. The char's greeting, then my message. For some reason..
Wait. I tried again just now and somehow I got it to work. I've tested on Mario many times, he's sick of me now.😅Thanks.
