### ISSUE TITLE
Deploy via docker

### ISSUE THREAD

**Issue by kazmil1** [drizzle-mizzle/CharacterAI-Discord-Bot#62]
Вообщем, попробовав развернуть бота через docker-compose бот вроде запускается, но беда в запуске хрома : 
![image](https://user-images.githubusercontent.com/130669059/231765389-a3858c3a-dac4-44b6-afb0-cee2a76844ef.png)
 (Разворачивал через Portainer, в stacks указав репо за основу)
Использовав команды по типу .ai set, find он ругается конечно мол браузер не загружен.
![image](https://user-images.githubusercontent.com/130669059/231766770-53b87db7-b622-4ea2-97f8-06de0a9c20bd.png)

**Comment by drizzle-mizzle** [comment]
Браузер и так запускается с этим аргументом. 
![Screenshot_20230413-182553_GitHub.jpg](https://user-images.githubusercontent.com/55811932/231773041-8202e624-23f3-49a0-a053-49c1022c90ff.jpg)
Без идей, чем помочь, так как сам докером пока не пользуюсь.
@Lymdun

**Comment by Lymdun** [comment]
См https://github.com/drizzle-mizzle/CharacterAI.Net-API-Wrapper/commit/b63b33161de41efa566082a35d8e40aaaa4ef42b

**Comment by kazmil1** [comment]
Ну в итоге плюнул на docker-compose который был в репо и развернул отдельный контейнер и поставил бота, работает все. Правда всё-же хотелось из "коробки" готовый compose :) Надеюсь, в будущем появиться. ))

**Comment by drizzle-mizzle** [comment]
Он там был только потому, что его сделал @raeyulca...
@kazmil1 если всё работает, можешь сделать пуш реквест со своим вариантом.
