### ISSUE TITLE
Can't find how to run bot

### ISSUE THREAD

**Issue by zoerodcig** [drizzle-mizzle/CharacterAI-Discord-Bot#63]
"Launch the bot:

Windows:
Simply run CharacterAI_Discord_Bot.exe"

There's no .exe files in the archive, how are you suppose to run it no Windows?

**Comment by drizzle-mizzle** [comment]
What do you mean there's no exe file?..
![Screenshot_20230413-181912_My Files](https://user-images.githubusercontent.com/55811932/231771642-f65a447b-cefd-446f-bae9-ca8f0c6ee81b.png)
