### ISSUE TITLE
uhh help pls

### ISSUE THREAD

**Issue by Ostap00** [drizzle-mizzle/CharacterAI-Discord-Bot#64]
![image](https://user-images.githubusercontent.com/98965062/231830265-fee4421e-ffe3-4d42-8823-ec336d5e40bb.png)
idk what to do

**Comment by drizzle-mizzle** [comment]
![image](https://user-images.githubusercontent.com/55811932/231849086-79b74c0a-f2e8-4e89-b3aa-f96d5c6cda9e.png)
