### ISSUE TITLE
what to do if it says "you have no power here"

### ISSUE THREAD

**Issue by PB0019c** [drizzle-mizzle/CharacterAI-Discord-Bot#71]
its working on my other server but not on main one

**Comment by drizzle-mizzle** [comment]
> what to do?

Read [Wiki](https://github.com/drizzle-mizzle/CharacterAI-Discord-Bot/wiki/Additional-configuration) || #67 
> If you want to give other users ability to configure a bot, give them a role and place it's name in discord_bot_role.
