### ISSUE TITLE
failure when downloading the browser

### ISSUE THREAD

**Issue by itleead** [drizzle-mizzle/CharacterAI-Discord-Bot#73]
I may not be able to download directly due to regional restrictions so I encountered a failure when downloading the browser, and the information is as follows:It may take some time on the first launch, because it will need to download a Chrome executable (~450mb).
If this process takes too much time, ensure you have a good internet connection (timeout = 20 minutes).

Downloading browser... System.Net.WebException: An error occurred while sending the request.
 ---> System.Net.Http.HttpRequestException: An error occurred while sending the request.
 ---> System.IO.IOException: The response ended prematurely.
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
 Can you please provide the manual download address and configuration?

**Comment by drizzle-mizzle** [comment]
You can just use any vpn.

But here it is: https://www.chromium.org/getting-involved/download-chromium/

You will need to download it and then specify a full path to executable file.
