### ISSUE TITLE
Bug: Swipes displayed on Discord differ from those on C.AI

### ISSUE THREAD

**Issue by malfoyslastname** [drizzle-mizzle/CharacterAI-Discord-Bot#76]
Reproduction steps: Have a conversation with a bot, swiping responses. Open conversation in browser. Selected swipes on C.AI are different from those on Discord (perhaps all first swipes?).

Not sure if this is a bug with C.AI or with the bot. I know C.AI has ongoing issues with swipes.

**Comment by malfoyslastname** [comment]
@drizzle-mizzle Please give me a chance to explain more clearly what the issue is by using an example.

Here's what we see on Discord. The user thinks they are responding to the second swipe (the bot choosing "yellow"), but in truth the user is responding to the first swipe (the bot choosing "blue").

![1682441623](https://user-images.githubusercontent.com/128472336/234349428-3d21e692-a1c5-4c24-9fa0-d25078bd7442.png)

Confirmed on the CAI conversation:

![1682441834](https://user-images.githubusercontent.com/128472336/234349584-154bca54-c3e8-4fbf-9625-9091732d5ecf.png)

**Comment by justkorudev** [comment]
hmm

**Comment by drizzle-mizzle** [comment]
Maybe you responded before character response was updated on discord?

**Comment by drizzle-mizzle** [comment]
I've checked right now, it performs swipe correctly

**Comment by malfoyslastname** [comment]
I'm reproducing this bug consistently, even when waiting after swiping.

![1682444087](https://user-images.githubusercontent.com/128472336/234358084-08809333-fb54-4c55-b21e-187cb993ceca.png)
![1682444236](https://user-images.githubusercontent.com/128472336/234358097-4f9f9a89-729d-44fa-aeb1-d8f12b552a57.png)

Here's the config I'm using:

```
{
    "discord_bot_token": "[redacted]",
    "char_ai_user_token": "[redacted]",

    "discord_bot_role": "Manage Character",
    "discord_bot_prefixes": [ ".ai5 "],
    "discord_private_category_name": "CAI PRIVATE CHANNELS",

    "default_audience_mode": 1,
    "audience_mode_quote_format": "((In response to: [{quote}]))\n",
    "audience_mode_username_format": "User [{username}] says: ",
    "default_no_permission_file": "nopower.gif",

    "private_chat_role_required": false,
    "use_character_avatar": true,
    "use_character_name": true,
    "description_in_playing_status": true,
    "allow_dm": true,

    "rate_limit": 10,
    "replies_delay": 1,
    "enable_swipe_buttons": true,
    "enable_stop_button": true,
    "buttons_remove_delay": 120,

    "auto_setup": true,
    "auto_char_id": "9QXQHXobHey-eZwvlMn4SftcVDqCtA_UKfek9QQ8zyE",

    "custom_chrome_directory": null,
    "custom_chrome_executable_full_path": null
}
```

**Comment by drizzle-mizzle** [comment]
Checked again. It just works. Can't reproduce your problem...
1: Reset + send message = Response A

![image](https://user-images.githubusercontent.com/55811932/234358173-3b905983-ffcf-4757-a084-f1a43d640f4d.png)

![image](https://user-images.githubusercontent.com/55811932/234358204-23651001-3935-465d-80a6-e1b770848ef2.png)

2: Swipe Response A to Reseponse B and responding on it = Response B is displayed as a chosen one in cAI chat:

![image](https://user-images.githubusercontent.com/55811932/234358546-71b17e17-9833-433f-b33a-f355145e560a.png)

![image](https://user-images.githubusercontent.com/55811932/234358597-11e97245-ad46-4e9c-8569-92ce3f59be09.png)

**Comment by drizzle-mizzle** [comment]
@malfoyslastname to begin with, try to simply update your bot version for the last one. I don't rembember changing anything that would affect this behavior, but just to make sure, download it and check if problem goes away.

**Comment by malfoyslastname** [comment]
I'll update to the latest version and report back.

**Comment by malfoyslastname** [comment]
This seems fixed on the latest version. Thank you and sorry for not doing that first.
