### ISSUE TITLE
A MessageReceived handler is blocking the gateway task.

### ISSUE THREAD

**Issue by ericmassak** [drizzle-mizzle/CharacterAI-Discord-Bot#79]
Hello! Does anyone know how to troubleshoot the error message in the title? I got my bot on the server, but after I tried to @ the bot, it started typing and then stopped without responding. I checked the .exe and it have the error in the title.

**Comment by drizzle-mizzle** [comment]
It's not really a error. That's the message that you usually get when either command takes too much time to execute, or when you simply have low internet speed.
What about character response – I guess it's simply stuck in "queue" and have responded to you after 2-4 minutes, if you didn't turned it off before it could

**Comment by ericmassak** [comment]
Thank you for your response. I currently have 385 Mbps download. Is there a
way to change the gateway timeout?

**Comment by ericmassak** [comment]
I imagine that this isn't helping the situation...
![image](https://user-images.githubusercontent.com/122337534/235174661-8cd62bd1-9098-4918-8f86-c7ca71580f4e.png)

**Comment by drizzle-mizzle** [comment]
> Thank you for your response. I currently have 385 Mbps download. Is there a way to change the gateway timeout?

Nope. Maybe the problem is also in speed of a hoster machine. I'll try to optimize the code a little.
