### ISSUE TITLE
why does this keep happening?

### ISSUE THREAD

**Issue by GENerationXVII** [drizzle-mizzle/CharacterAI-Discord-Bot#83]
21:10:58 Gateway     Discord.WebSocket.GatewayReconnectException: Server requested a reconnect
   at Discord.ConnectionManager.<>c__DisplayClass29_0.<<StartAsync>b__0>d.MoveNext()
21:10:58 Gateway     Disconnecting
21:10:58 Gateway     Disconnected
21:10:59 Gateway     Connecting
21:10:59 Gateway     Resumed previous session
21:10:59 Gateway     Connected

Whenever this happens, the bots stop replying. Btw, how do I reboot the bots?

**Comment by drizzle-mizzle** [comment]
This is not Discord.Net repository, ask here:
https://github.com/discord-net/Discord.Net

Never noticed it would affect the work of the bot in any way, tho.
