### ISSUE TITLE
reboot

### ISSUE THREAD

**Issue by GENerationXVII** [drizzle-mizzle/CharacterAI-Discord-Bot#84]
is reboot .ai reboot? cuz idk if its working for me

**Comment by drizzle-mizzle** [comment]
What.

**Comment by GENerationXVII** [comment]
like how do i reboot command

**Comment by drizzle-mizzle** [comment]
I have no idea what is your question about, but `reboot` command does simply relaunch web browser inside the application. It can be useful sometimes, when Cloudflare marks browser as a "suspicious", and character stops responding at all.

**Comment by Mj83621** [comment]
I think he was reading the commands and saw the reboot, but he thinks the name is different because in discord, you have to type .ai reboot to do it. he probably thinks that its a different command. @GENerationXVII  its called a reboot command, just like he said, it relaunches the browser in the bot. every command must be executed using the .ai prefix. the command is not called .ai reboot. just reboot.

**Comment by drizzle-mizzle** [comment]
Btw, `.ai` is an optional prefix that you can change in your config file. Also, commands can be executed with direct `@mention`.

**Comment by Mj83621** [comment]
i know, but since he opened this issue because he didnt know how the prefix was diffrent, he probaly didnt change the prefix.

**Comment by drizzle-mizzle** [comment]
yep, that's why I added it

**Comment by GENerationXVII** [comment]
so if i want to reboot, what do i do

**Comment by drizzle-mizzle** [comment]
oh...

**Comment by drizzle-mizzle** [comment]
@GENerationXVII what do you mean by "reboot"?

**Comment by GENerationXVII** [comment]
how do i do the reboot command

**Comment by drizzle-mizzle** [comment]
You just execute it as any other command...

![20221025_105729](https://user-images.githubusercontent.com/55811932/235492532-190daf74-62a1-4937-a571-99224668a53b.jpg)

**Comment by GENerationXVII** [comment]
LMAOOOOO so on Discord, it would be .ai reboot? because that didnt work for me. sorry for the trouble :(

**Comment by drizzle-mizzle** [comment]
It worket, there's simply no response in discord itself, because it was mostly for debug purposes.
I'll change that.
