### ISSUE TITLE
chmod: changing permissions of './CharacterAI_Discord_Bot': Read-only file system[BUG]

### ISSUE THREAD

**Issue by SpunkenYataa** [drizzle-mizzle/CharacterAI-Discord-Bot#92]
I get this error code when i try to run the command "sudo chmod 777 ./CharacterAI_Discord_Bot"

**Comment by drizzle-mizzle** [comment]
That is not a bug. Just move your bot folder to another directory. 
https://www.cyberciti.biz/faq/move-a-directory-linux-command/
You better place it in `~`:

  ![image](https://user-images.githubusercontent.com/55811932/236691842-5391ce95-a8f5-4751-a5df-48a14d03ebc8.png)

**Comment by SpunkenYataa** [comment]
Will try this, thank you for quick response im new to linux lol.
