### ISSUE TITLE
[BUG] The bot not replying and can't run any command except '.ai set'

### ISSUE THREAD

**Issue by TheSkatt** [drizzle-mizzle/CharacterAI-Discord-Bot#94]
- [x] I am using the [latest version](https://github.com/drizzle-mizzle/CharacterAI-Discord-Bot/releases/latest) of the program.
- [x] I have read the [Known-issues](https://github.com/drizzle-mizzle/CharacterAI-Discord-Bot#known-issues) section and [Issues](https://github.com/drizzle-mizzle/CharacterAI-Discord-Bot/issues) page, and made sure that this problem was not already described elsewhere.
- [x] I have followed the all the [how to set up](https://github.com/drizzle-mizzle/CharacterAI-Discord-Bot/wiki/How-to-set-up) step properly.

### Describe the bug:
The only command I can run is '.ai set' and the bot can't even reply message in chat(Even a Administrator perms)

### Screenshots:

![Capture1](https://github.com/drizzle-mizzle/CharacterAI-Discord-Bot/assets/118121069/87d441db-99e7-42c2-8c12-203a45233b42)
![Capture2](https://github.com/drizzle-mizzle/CharacterAI-Discord-Bot/assets/118121069/c602cc2a-7362-42ff-bd9a-aebce797bc6e)

### Additional info:
- My OS is Window 10.
- PC located in Thailand

**Comment by drizzle-mizzle** [comment]
I'm sure it has to do something with your permissions settings, check twice.
Even if everything would broke, at least the `ping` command would 200% work, if your bot has permission to write in channel.

**Comment by TheSkatt** [comment]
> I'm sure it has to do something with your permissions settings, check twice. Even if everything would broke, at least the `ping` command would 200% work, if your bot has permission to write in channel.

I have followed what you suggest. I give every single perms to the bot and try the '.ai ping' command and it still not working.

Screenshot:
![Capture3](https://github.com/drizzle-mizzle/CharacterAI-Discord-Bot/assets/118121069/47a893a1-55ff-4f6d-bfe8-877c1f84a842)

Also, thank you for your response. 🙏

**Comment by drizzle-mizzle** [comment]
Maybe you changed your prefixes in the config file and forgot about that?
Or accidentaly set very big replies delay? 
![image](https://github.com/drizzle-mizzle/CharacterAI-Discord-Bot/assets/55811932/a79ef684-65ca-4993-85c7-781c06b24f80)
![image](https://github.com/drizzle-mizzle/CharacterAI-Discord-Bot/assets/55811932/502d43b6-0e38-4861-8486-9b622ecd93bd)

**Comment by TheSkatt** [comment]
> Maybe you changed your prefixes in the config file and forgot about that? Or accidentaly set very big replies delay? ![image](https://user-images.githubusercontent.com/55811932/238059618-a79ef684-65ca-4993-85c7-781c06b24f80.png) ![image](https://user-images.githubusercontent.com/55811932/238059700-502d43b6-0e38-4861-8486-9b622ecd93bd.png)

No I didn't. This is my config file. (I setting only "discord_bot_token" and  "char_ai_user_token")

Config Text:
{
    "discord_bot_token": "MTEwNjI2ODg5MDA1NDU0MTM4Ng.GvBXXd.ebwZ1fKNcmR0T6Bb8ykvUbV_Eq4rpXY4h5TRpg",
    "char_ai_user_token": "d826dab9920b68edee5711e083e2dcddeac668e0",

    "discord_bot_role": "Manage Character",
    "discord_bot_prefixes": [ ".ai ", "!!" ],
    "discord_private_category_name": "CAI PRIVATE CHANNELS",

    "default_audience_mode": 0,
    "audience_mode_quote_format": "((In response to: [{quote}]))\n",
    "audience_mode_username_format": "User [{username}] says: ",
    "default_no_permission_file": "nopower.gif",

    "private_chat_role_required": false,
    "use_character_avatar": true,
    "use_character_name": true,
    "description_in_playing_status": true,
    "allow_dm": true,

    "rate_limit": 10,
    "default_replies_delay": 1,
    "enable_swipe_buttons": true,
    "enable_stop_button": true,
    "buttons_remove_delay": 120,

    "auto_setup": true,
    "auto_char_id": "6HhWfeDjetnxESEcThlBQtEUo0O8YHcXyHqCgN7b2hY",

    "custom_chrome_directory": null,
    "custom_chrome_executable_full_path": null,
    "public_mode": false,
    "hoster_discord_id": null,

    "enable_translate_button": false,
    "deepl_api_token": "",
    "default_translate_language": "ru",

    "discord_error_log_channel_id": null
}

**Comment by drizzle-mizzle** [comment]
DM me in discord

**Comment by drizzle-mizzle** [comment]
@kusumiluvsu 
> i actually ended up having the same problem and trying to make multiple bots, but it didn't work.

His problem is not anyhow related to "having a multiple bots". He was simply unable to establish a proper connection with cAI servers, and we could not find a way to fix it.
If you have one bot working, the second one will work too. If it doesn't you have simply missed some of the steps. I would bet on that you did not give it needed permmission on your server.
