### ISSUE TITLE
[BUG] Triggered a command after mentioning the bot

### ISSUE THREAD

**Issue by Rentako** [drizzle-mizzle/CharacterAI-Discord-Bot#95]
- [x] I am using the [latest version](https://github.com/drizzle-mizzle/CharacterAI-Discord-Bot/releases/latest) of the program.
- [x] I have read the [Known-issues](https://github.com/drizzle-mizzle/CharacterAI-Discord-Bot#known-issues) section and [Issues](https://github.com/drizzle-mizzle/CharacterAI-Discord-Bot/issues) page, and made sure that this problem was not already described elsewhere.

### Describe the bug:
Whenever you mention the bot name and type the command without using the prefixes, it will trigger the command

### Screenshots:
![image](https://github.com/drizzle-mizzle/CharacterAI-Discord-Bot/assets/133369508/18a25f9f-5ca8-410c-88dd-93e8d3eec9c0)

**Comment by drizzle-mizzle** [comment]
Not the bug, just the way it works, and it's noted in [Important-Notes](https://github.com/drizzle-mizzle/CharacterAI-Discord-Bot/wiki/Important-Notes)
Mention prefix and symbolic prefixes are even. Don't want to change it, I'll better simply transfer commands to the slash-based ones someday later.
