### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by RainManteehee** [drizzle-mizzle/CharacterAI-Discord-Bot#97]
- [ ] I am using the [latest version](https://github.com/drizzle-mizzle/CharacterAI-Discord-Bot/releases/latest) of the program.
- [ ] I have read the [Known-issues](https://github.com/drizzle-mizzle/CharacterAI-Discord-Bot#known-issues) section and [Issues](https://github.com/drizzle-mizzle/CharacterAI-Discord-Bot/issues) page, and made sure that this problem was not already described elsewhere.

### Describe the bug:
When opening the exe I get this message: 
16:06:28 Discord     Discord.Net v3.10.0 (API v10)
16:06:28 Gateway     Connecting
16:06:29 Gateway     System.Exception: WebSocket connection was closed
 ---> Discord.Net.WebSocketClosedException: The server sent close 4014: "Disallowed intent(s)."
   at Discord.Net.WebSockets.DefaultWebSocketClient.RunAsync(CancellationToken cancelToken)
   --- End of inner exception stack trace ---
   at Discord.ConnectionManager.WaitAsync()
   at Discord.WebSocket.DiscordSocketClient.OnConnectingAsync()
   at Discord.ConnectionManager.ConnectAsync(CancellationTokenSource reconnectCancelToken)
   at Discord.ConnectionManager.<>c__DisplayClass29_0.<<StartAsync>b__0>d.MoveNext()
16:06:29 Gateway     Disconnecting

### Steps to reproduce the behavior:
1. when I opened the exe after following everything else it happened
### Expected behavior:
...

### Additional info:
- Windows

**Comment by drizzle-mizzle** [comment]
> * [ ]  I am using the [latest version](https://github.com/drizzle-mizzle/CharacterAI-Discord-Bot/releases/latest) of the program.
> * [ ]  I have read the [Known-issues](https://github.com/drizzle-mizzle/CharacterAI-Discord-Bot#known-issues) section and [Issues](https://github.com/drizzle-mizzle/CharacterAI-Discord-Bot/issues) page, and made sure that this problem was not already described elsewhere.

These are not just for show, you know?

## Try to do this:
1. Read the error:
> The server sent close 4014: "Disallowed intent(s)."
2. Read an issue-template:
> I have read the [Known-issues](https://github.com/drizzle-mizzle/CharacterAI-Discord-Bot#known-issues) section and [Issues](https://github.com/drizzle-mizzle/CharacterAI-Discord-Bot/issues) page, **`and made sure that this problem was not already described elsewhere.`**
3. Use the advice:<br>
![image](https://github.com/drizzle-mizzle/CharacterAI-Discord-Bot/assets/55811932/7246faa2-feb3-4cf9-978d-7996ed8c7407)
4. And here we go:
https://github.com/drizzle-mizzle/CharacterAI-Discord-Bot/issues/78
